plugins { id 'com.android.application' }

android {
    namespace 'com.nori.kage'
    compileSdk 36
    defaultConfig {
        applicationId 'com.nori.kage'
        minSdk 26
        targetSdk 35
        versionCode 12
        versionName '11.0.1'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    packaging { resources.excludes += ['/META-INF/{AL2.0,LGPL2.1}'] }
}
dependencies {
    implementation project(':capacitor-android')
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.core:core:1.17.0'
    implementation 'androidx.annotation:annotation:1.9.1'
}
def capBuild = file('capacitor.build.gradle')
if (capBuild.exists()) apply from: capBuild